### ISSUE TITLE
bug: example suggests wrong usage of variables

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-srv_ssh#3]
current:

```
- hosts: all
  roles:
    - role: while_true_do.srv_ssh
      wtd_srv_ssh_conf.Port: "19022"
      wtd_srv_ssh_conf.PasswordAuthentication: "no"
```

fixed:

```
- hosts: all
  roles:
    - role: while_true_do.srv_ssh
      wtd_srv_ssh_conf
        Port: "19022"
        PasswordAuthentication: "no"
```
